version: '3'
services:
  account:
    image: "account"
    ports:
      - "8081:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka
  bank:
    image: "bank"
    ports:
      - "8082:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka
  gateway:
    image: "gateway"
    ports:
      - "8083:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka
  configuration:
    image: "configuration"
    ports:
      - "8084:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka
  service-discovery:
    image: "yunterry/spring-cloud-eureka"
    ports:
      - "8761:8761"