spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: account
        uri: lb://account
        predicates:
        - Path=/accounts/, /account/{id}

      - id: bank
        uri: lb://bank
        predicates:
        - Path=/bank/{id}